### PR TITLE
close the file stream

### PR DESCRIPTION
**Pull request by strawposter**
Hi,

the output file is locked without closing the stream

### CODE REVIEW

**Comment by jrfonseca** [comment]
`self.fp` might be `sys.stdout`, and one should never close `sys.stdout`, so this can't go in as-is.  The same function that opens the `fp` must close it.

But I don't understand why this even matters: isn't the file automatically closed when the `gprof2dot.py`'s `main` function terminates?

Does this change really make a difference?  On which OS is this?

**Comment by strawposter** [comment]
OS - windows 7 64x

This problem appeared when I used a small script

- final png is not created
- It does not delete intermediate files in the current directory

# coding: UTF-8

def example():
    a = 3
    b = 2
    return a + b


try:
    import cProfile as profile
except ImportError:
    import profile

import os    
import sys 
import gprof2dot
import subprocess 

LOGSTATS = 'stats.stats'
DOT = 'output.dot'
PNG = 'output.png'
 
profile.run('example()', LOGSTATS)

sys.argv = ['', '-o', DOT, '-f', 'pstats', LOGSTATS]

gprof2dot.main()

args = ["c:\\Program Files (x86)\\Graphviz2.38\\bin\\dot.exe", DOT, '-Tpng', '-o', PNG]
result = subprocess.call(args)

if result == 0:
    filelist = [ f for f in os.listdir(".") if f.endswith(".stats") or f.endswith(".dot")]
    for f in filelist:
        os.remove(f)

P.S.:
after the corrections, it worked

**Comment by jrfonseca** [comment]
> import gprof2dot

I understand the problem now.

But I'm not sure I want to support using gprof2dot as a library.  Googling for `import gprof2dot` shows that this is not an isolated case.  Still, supporting gprof2dot as library was something I never intented, and probably not worth my while -- I can't guarantee binary compatibility.

Note however you can easily invoke gprof2dot doing:

    subprocess.call([sys.executable, 'gprof2dot.py', ....]

**Comment by strawposter** [comment]
I think you're a little complicate the problem solution

**Comment by jrfonseca** [comment]
I can't afford much time to maintain gprof2dot, and I don't want to deal with the influx of bugs that are bound to happen if people continue to use gprof2dot via import.

So, even though I could fix this particular issue easily, I rather to make it crystal clear that this is not supported, and prevent other issues from ever arising in future, as done in commit 2529b4543bbafaa896b76630007be3d319affb33.

So while appreciate you have gone through the trouble of diagnosing and proposing a fix, I'm afraid on this occasion I can't accept it..

**Pull request closed without merging**
